services:
  integrations_service_db:
    image: mongo
    restart: always
    ports:
      - 5001:27017
    volumes:
      - ./docker_directories/integrations_service:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: integrations_service_db
      MONGO_INITDB_ROOT_PASSWORD: aRanDomPasSwORD
      MONGO_INITDB_DATABASE: integrations
