networks:
  app-network:
    driver: bridge

  internal-network:
    driver: bridge
    internal: true

  integrations-service-network:
    driver: bridge
    internal: true

services:
  gateway-db:
    image: postgres:13
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - gateway-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "kong", "-U", "kong" ]
      interval: 5s
      timeout: 30s
      retries: 3
    networks:
      - internal-network

  gateway-migrations:
    image: kong:latest
    depends_on:
      - gateway-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: gateway-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    command: "kong migrations bootstrap"
    networks:
      - internal-network

  gateway:
    image: kong:latest
    depends_on:
      - gateway-db
      - gateway-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: gateway-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
      - "8444:8444"
    restart: unless-stopped
    networks:
      - internal-network
      - app-network

  integrations-service-db:
    extends:
      file: ./backend/integrations_service/docker-compose.yml
      service: integrations-service-db
    ports: []
    networks:
      - integrations-service-network

  integrations-service:
    extends:
      file: ./backend/integrations_service/docker-compose.yml
      service: integrations-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --root-path /integrations
    ports: []
    networks:
      - integrations-service-network
      - internal-network

volumes:
  gateway-db-data:
  gateway-config:
