services:
  integrations_service_db:
    image: redis
    restart: always
    ports:
      - 5001:6379
    environment:
      REDIS_PASSWORD: aRanDomPasSwORD
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
