services:
  integrations-service-token-db:
    extends:
      file: ./docker-compose.base.yml
      service: integrations-service-token-db
    ports:
      - "5001:6379"

  integrations-sync-db:
    extends:
      file: ./docker-compose.base.yml
      service: integrations-sync-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sync
    ports:
      - "5002:27017"

  integrations-service:
    extends:
      file: ./docker-compose.base.yml
      service: integrations-service
    environment:
      TOKEN_DATABASE_CONNECTION_STRING: "redis://:redispass@integrations-service-token-db:6379/0"
      SYNC_DATABASE_CONNECTION_STRING: "mongodb://root:example@integrations-sync-db:27017"
      TIKTOK_TOKEN_URI: https://open.tiktokapis.com/v2/oauth/token/
      TIKTOK_REDIRECT_URI: https://concrete-troll-brightly.ngrok-free.app/integrations/tiktok/callback
      TIKTOK_CLIENT_KEY: sbawgik9wknh769zea
      TIKTOK_CLIENT_SECRET: ntnIeAlvnKPC6tTIXTQpsi4kws3D7ewv
    volumes:
      - .:/usr/src
    ports:
        - "5000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
