services:
  integrations-service-db:
    image: redis:latest
    command: redis-server --requirepass redispass

  integrations-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - integrations-service-db
    environment:
      DATABASE_CONNECTION_STRING: "redis://:redispass@integrations-service-db:6379/0"
      TIKTOK_TOKEN_URI: https://open.tiktokapis.com/v2/oauth/token/
      TIKTOK_REDIRECT_URI: https://octopus-immense-truly.ngrok-free.app/integrations/tiktok/callback
      TIKTOK_CLIENT_KEY: sbawgik9wknh769zea
      TIKTOK_CLIENT_SECRET: ntnIeAlvnKPC6tTIXTQpsi4kws3D7ewv
    volumes:
      - .:/usr/src
    ports:
        - "5000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
